### ISSUE TITLE
[General] I have no idea what I'm doing

### ISSUE THREAD

**Issue by agustinyabo** [agustinyabo/PWLdynamics.jl#2]
J'ai fait une première version, j'imagine qu'il faut que tu fasses quelque chose de ton côté ?

Gracias !

**Comment by agustinyabo** [comment]
https://agustinyabo.github.io/PWLdynamics.jl/dev/index.html

C'est déjà pas mal !

**Comment by ocots** [comment]
@agustinyabo Merci nickel !

J'ai fait le nécessaire, bientôt, on verra ton exemple apparaitre dans le menu Applications. @jbcaillau

**Comment by agustinyabo** [comment]
Ça y est !

Et c'est normal que le lien pointe vers "https://agustinyabo.github.io/PWLdynamics.jl/stable/" alors que les autres exemples sont dans le domaine "https://control-toolbox.org/"

**Comment by agustinyabo** [comment]
Nah, c'est bon, je garde dans mon répertoire, je vous fait pas assez confiance :male_detective:
